version: '2'
services:

  producer:
    build: ./jogo-producer-api
    container_name: "producer"
    ports:
      - 3000:3000
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092

  consumer:
    build: ./jogo-consumer-api
    container_name: "consumer"
    ports:
      - 3001:3001
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      PALAVRAS_POSITIVAS: '["bom", "legal", "ótimo", "massa"]'
      PALAVRAS_NEGATIVAS: '["fraco", "ruim", "péssimo"]'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: "zookeeper"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - ./volumes/zookeeper-data:/var/lib/zookeeper/data
      - ./volumes/zookeeper-log:/var/lib/zookeeper/log
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: "kafka"
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./volumes/kafka-data:/var/lib/kafka/data

networks:
  default:
    name: jogo-net